apiVersion: apps/v1
kind: Deployment
metadata:
  name: realchat-backend
  namespace: realchat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realchat-backend
  template:
    metadata:
      labels:
        app: realchat-backend
    spec:
      containers:
        - name: backend
          image: realchat/backend:latest
          env:
            - name: DATABASE_URL
              value: "ecto://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: realchat-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: realchat-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: realchat-config
                  key: POSTGRES_DB
            - name: SCYLLA_CONTACT_POINTS
              valueFrom:
                configMapKeyRef:
                  name: realchat-config
                  key: SCYLLA_CONTACT_POINTS
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: realchat-config
                  key: REDIS_URL
            - name: GUARDIAN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: realchat-secrets
                  key: guardian-secret
            - name: MIX_ENV
              valueFrom:
                configMapKeyRef:
                  name: realchat-config
                  key: MIX_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: realchat-config
                  key: PORT
            - name: PHX_SERVER
              value: "true"
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: realchat
spec:
  selector:
    app: realchat-backend
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: realchat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realchat-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
